
export const CLASSIFICATION_CLASSES = {
	"The Eiffel Tower": 0,
	"The Great Wall of China": 1,
	"aircraft carrier": 2,
	"airplane": 3,
	"alarm clock": 4,
	"ambulance": 5,
	"angel": 6,
	"animal migration": 7,
	"ant": 8,
	"anvil": 9,
	"apple": 10,
	"arm": 11,
	"asparagus": 12,
	"axe": 13,
	"backpack": 14,
	"banana": 15,
	"bandage": 16,
	"barn": 17,
	"baseball": 18,
	"baseball bat": 19,
	"basket": 20,
	"bat": 21,
	"bathtub": 22,
	"beach": 23,
	"bear": 24,
	"beard": 25,
	"bed": 26,
	"bee": 27,
	"belt": 28,
	"bench": 29,
	"bicycle": 30,
	"binoculars": 31,
	"bird": 32,
	"birthday cake": 33
};